### ISSUE TITLE
LitData feedbacks

### ISSUE THREAD

**Issue by tchaton** [cma2015/DEM#1]
Hey there,

I am the main author of LitData. I wondered if you had any feedbacks to improve the library.

Best regards,
T.C

**Comment by WuChenh** [comment]
> Hey there,
> 
> I am the main author of LitData. I wondered if you had any feedbacks to improve the library.
> 
> Best regards, T.C

@tchaton Thank you and other contributors for your amazing work!
I wonder if it is possible to add cross validation and graph structure data support (i.e. PyG compatability) to LitData. In addition, when using compressed optimized datasets, is it possible to prevent the generation of extracted files in the same directory?
Best regards,
C.W.
